[tools]
bat = "latest"
bun = "latest"
fzf = "latest"
just = "latest"
lazygit = "latest"
lsd = "latest"
node = "latest"
python = "latest"
rust = "latest"
starship = "latest"
uv = "latest"
neovim = "latest"
jj = "latest"
zoxide = "latest"
